FROM node:16-alpine

ENV TZ=Asia/Seoul

ENV NODE_ENV=production

RUN yarn global add lerna

COPY package.json .

RUN yarn

COPY tsconfig.json .
COPY packages/library ./packages/library
COPY packages/shared ./packages/shared
COPY packages/server ./packages/server

COPY lerna.json .

RUN lerna bootstrap

WORKDIR /packages/server

EXPOSE 5000

ENTRYPOINT yarn prisma generate && npm run prod
