FROM nginx:alpine

RUN mkdir /app

WORKDIR /app

RUN mkdir ./dist

COPY packages/webapp/dist ./dist

RUN rm /etc/nginx/conf.d/default.conf

COPY packages/webapp/nginx.conf /etc/nginx/conf.d/nginx.conf

EXPOSE 80

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
