FROM node:16-alpine

ENV TZ=Asia/Seoul

ENV DEBUG=socket.io:client*,socket.io:socket*

ENV NODE_ENV=production

RUN yarn global add lerna

COPY package.json .

RUN yarn

COPY tsconfig.json .
COPY packages/library ./packages/library
COPY packages/shared ./packages/shared
COPY packages/socketServer ./packages/socketServer

COPY lerna.json .

RUN lerna bootstrap

WORKDIR /packages/socketServer

EXPOSE 5001

ENTRYPOINT npm run prod
