name: CI
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  NODE_VERSION: 'lts/*'
  NPM_REGISTRY_URL: 'https://registry.npmjs.org'

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - run: echo "check-dependencies"

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "lint"
  
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"

  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "chromatic-deployment"
