name: List PRs in a specific milestone

on:
  pull_request:
    types:
      - opened

jobs:
  list_prs:
    runs-on: ubuntu-latest
    if: github.event.pull_request.title == 'My Special PR' # Replace with your desired PR title

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install jq

    - name: Fetch milestone number
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MILESTONE_TITLE: 'Your Milestone Title' # Replace with your milestone title
      run: |
        response=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$GITHUB_REPOSITORY/milestones")
        milestone_number=$(echo "$response" | jq ".[] | select(.title == \"$MILESTONE_TITLE\") | .number")
        echo "MILESTONE_NUMBER=$milestone_number" >> $GITHUB_ENV

    - name: Fetch PRs in milestone
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        response=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=all&per_page=100")
        prs_in_milestone=$(echo "$response" | jq ".[] | select(.milestone.number == $MILESTONE_NUMBER) | {number: .number, title: .title, url: .html_url}")
        echo "PRs in milestone $MILESTONE_TITLE:"
        echo "$prs_in_milestone"
