name: Deploy application

on:
  push

env:
  SOMETHING: cool
  I18N_ASSET_DIRECTORY: i18n-assets

jobs:
  deploy_api_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set short commit hash
        id: vars
        run: echo "::set-output name=short_commit_hash::$(git rev-parse --short HEAD)"

      - name: Get release version
        run: echo "DEPLOY_VERSION=v$(cat ./lerna.json | jq -r '.version')" >> $GITHUB_ENV
      
      - name: Check i18n asset file existence
        id: check-i18n-assets
        run: |
          if [ -f ${{ env.I18N_ASSET_DIRECTORY }}/**/common-web.json ]; then
            echo "I18N_ASSET_EXISTS=true" >> $GITHUB_ENV
          fi
        
      - name: Deploy i18n asset files
        if: env.I18N_ASSET_EXISTS == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_REGION: ap-northeast-2
        run: |
          aws s3 cp ${{ env.I18N_ASSET_DIRECTORY }} s3://ronnie.test/locales/${{ env.DEPLOY_VERSION }} --recursive

