name: Update CHANGELOG with PRs in milestone

on:
  pull_request:
    types:
      - labeled

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'release' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Extract milestone title from branch name
        run: |
          milestone_title=$(echo "${{ github.event.pull_request.head.ref }}" | sed -E 's/^release\/(.*)/\1/')
          echo ${{ github.event.pull_request.head.ref }}
          echo "MILESTONE_TITLE=$milestone_title" >> $GITHUB_ENV

      - name: Request ChatGPT to write down CHANGELOG content
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: |
          response=$(curl -X POST https://api.openai.com/v1/chat/completions \
           -H "Content-Type: application/json" \
           -H "Authorization: Bearer $OPENAI_KEY" \
           -d '{
              "model": "gpt-3.5-turbo",
              "messages": [
                { 
                  "role": "user",
                  "content": "Please write down a markdown content based on this data\n```\n{\n  \"title\": \"2313\",\n  \"number\": 133,\n  \"url\": \"https://github.com/jaehyeon48/github-actions-test/pull/133\",\n  \"package\": \"app-installation-1\"\n}\n{\n  \"title\": \"merge test\",\n  \"number\": 112,\n  \"url\": \"https://github.com/jaehyeon48/github-actions-test/pull/112\",\n  \"package\": \"reivews\"\n}\n```\nin the format like this\n```\n### package\n\n- title [#number](url)\n```"
                }
              ]
            }' 
          )
          changelog_content=$(echo $response | jq -r '.choices[].message.content')
          printf '\n%s\n\n' "## $MILESTONE_TITLE" >> changelog_tmp.md
          printf '%s\n' "$(echo "$changelog_content" | sed 's/^"\|"$//g')" >> changelog_tmp.md

          sed -i '/^# CHANGELOG/ r changelog_tmp.md' CHANGELOG.md
          rm changelog_tmp.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md with PRs in milestone $MILESTONE_TITLE"
          git push
