name: Update CHANGELOG with PRs in milestone

on:
  pull_request:
    types:
      - opened
      - labeled

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'release' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Extract milestone title from branch name
        run: |
          milestone_title=$(echo "${{ github.event.pull_request.head.ref }}" | sed -E 's/^release\/(.*)/\1/')
          echo ${{ github.event.pull_request.head.ref }}
          echo "MILESTONE_TITLE=$milestone_title" >> $GITHUB_ENV

      - name: Fetch PRs in milestone and update CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/search/issues?q=milestone:v13.1.2+type:pr+repo:$GITHUB_REPOSITORY")
          prs_in_milestone=$(echo "$response" | jq -r '.items[] | select(.state == "open") | "- \(.title) \(.number) \(.url)"')
          echo $prs_in_milestone >> CHANGELOG.md

          echo -e "\n## $MILESTONE_TITLE\n" >> CHANGELOG.md
          for pr in "${prs_in_milestone[@]}"
          do
            echo "$pr" >> CHANGELOG.md
          done

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md with PRs in milestone $MILESTONE_TITLE"
          git push