name: Test-workflow

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  frontend:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'frontend')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Install lerna
        run: yarn global add lerna

      - name: Cache node modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install All Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: lerna bootstrap
