name: Test-workflow

on:
  pull_request:
    branches: [main]
    types: [closed, labeled]

jobs:
  frontend:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels, 'frontend')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
