name: Test-workflow

on:
  pull_request:
    branches: [main]
    types: [closed, labeled]

jobs:
  frontend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: testtest
        run: |
          echo "${{github.event.pull_request}}"
