name: Update CHANGELOG

on:
  pull_request:
    types:
      - labeled

env:
  COMMIT_USER_EMAIL: developer@triple-corp.com
  COMMIT_USER_NAME: triple-frontend[bot]
  CURRENT_VERSION: ${{ github.event.pull_request.milestone.title }}

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'release' }}
    steps:
      - name: Check if a milestone exists on PR
        run: |
          if [[ $(echo ${{ github.event.pull_request.milestone }}) == "" ]]; then
            echo "마일스톤을 등록해 주세요."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Execute Changelog JavaScript
        run: node scripts/changelog.js

